### ISSUE TITLE
If borges crashes, jobs are not sent to the dead letter queue

### ISSUE THREAD

**Issue by smola** [src-d/borges#112]
See https://github.com/src-d/borges/issues/26
When borges finds an error and rejects a job (ack + err) it sends the job to the dead letter queue. However, this is not being done when borges crashes.

**Comment by ajnavarro** [comment]
Related with this issue:
- Now we can cancel Borges processes using the go-git context.
- In Rabbit, if a job is not Ack'ed and the connection is lost, this [job is automatically re-queued](https://www.rabbitmq.com/tutorials/tutorial-two-python.html):
    > If a consumer dies (its channel is closed, connection is closed, or TCP connection is lost) without 
    sending an ack, RabbitMQ will understand that a message wasn't processed fully and will re-queue it. If 
    there are other consumers online at the same time, it will then quickly redeliver it to another consumer. 
    That way you can be sure that no message is lost, even if the workers occasionally die.

    > There aren't any message timeouts; RabbitMQ will redeliver the message when the consumer dies. It's 
    fine even if processing a message takes a very, very long time.

Also, if we want to send all in-process messages to the dead letter, we should implement this logic ourselves [because](https://www.rabbitmq.com/dlx.html):

>Messages from a queue can be 'dead-lettered'; that is, republished to another exchange when any of 
the following events occur:
> - The message is rejected (basic.reject or  basic.nack) with requeue=false,
> - The TTL for the message expires; or
> - The queue length limit is exceeded.

The conclusion of all of this is:
- If a consumer loses the connection with the broker, we should stop all the workers immediately, because other consumer could start processing this same jobs. Is not a big problem because we have locks, but we should do it in that way.
- If a consumer panics, all the jobs will be re-queued. We cannot avoid it sending before processing the job to the dead letter, because is not possible remove a message from a queue from id in rabbit. In this case, we should capture the panic, and then send the job to the dead letter queue.

**Comment by ajnavarro** [comment]
As I can see, is not possible to know if a message comes back to the queue due a connection error, so we cannot do any logic in rabbit side if a consumer dies.

**Comment by erizocosmico** [comment]
Taking this (can't assign myself right now)

**Comment by erizocosmico** [comment]
As discussed IRL with @ajnavarro, the cleanest solution for now seems to be the following:

- Every time a job is taken from the queue, write in the database a field with the timestamp when it was taken.
- When a worker takes a job, checks if said timestamp is prior to the updated_at field. If it's not, it rejects it and sends it to the dead letter queue and moves onto the next job.

While this requires one more read and write in the process, it's the only way we can ensure tolerance to any kind of possible failures given the limitations of rabbitMQ and the impossibility of catching all panics everywhere in the code.

**Comment by erizocosmico** [comment]
PR: #141
