### ISSUE TITLE
mark one repository as main in for each root group

### ISSUE THREAD

**Issue by smola** [src-d/borges#117]
Initial heuristic will be:
* Check is_fork (when it is available) https://github.com/src-d/rovers/issues/144
* The one with more PRs.
* The one with more commits.
* If there is a tie on everything, pick the lowest ULID.

This will be implemented in borges:
* add is_fork to the database https://github.com/src-d/borges/pull/122
* mark is_fork in remotes in rooted repository

**Comment by bzz** [comment]
Heuristics looks good, quick question though - where would this information be stored?

Asking as it seems to be needed as part of the schema in https://github.com/src-d/berserker/issues/20#issue-244343298 

In my current understanding this implies that it should be part of a self-contained rooted repository inside the `.siva` file, in order to be able to match the design goal of avoiding an external extractor queuing the DB in Berserker. Is that correct?

**Comment by smola** [comment]
Since this heuristic is subject to lots of changes, it would be better to solve it at read time. So we should implement this now in `src-d/berkser`.

**Comment by bzz** [comment]
So, this issue on Borges becomes about just storing `is_fork` information in RootedRepo config, per each original repo ULID. 

Is there a particular format we have in mind? 

AFAIK it's KV with composite key and ability to set/unset key and value by regex

`git config <section>.<sub-section>.<keyname> value`
