### ISSUE TITLE
Create a borges-lite command

### ISSUE THREAD

**Issue by ajnavarro** [src-d/borges#174]
To make the task of make rooted repositories on siva files more easy, we need a new borges command that would be able to get a list of urls from a file, fetch them and save to rooted repositories, without dependencies of rabbit or postgres.

**Comment by erizocosmico** [comment]
- [ ] Make borges work without a database if needed
- [ ] Make borges work without a queue if needed
- [ ] Make command to convert from git repositories to siva files

**Comment by erizocosmico** [comment]
### Convert command

Since what we want is a conversion command, I think the interface should be something like this:

```
borges convert --source=file --file=file.txt
borges convert --dir /path/to/repos # --source=directory implied
borges convert --dir /path/to/repos --output /path/to/siva/files/dir
```

With `--dir` you treat each top-level folder in that folder as a repository and process it.
With `--file` you treat each line as a path to a repository and process it.

The rationale behind not using `borges producer` and `borges consumer` is for clarity towards the user. With `convert` you know the only think you're doing is converting with no other side effects than the output files whereas `consumer` and `producer` are 2 commands, which is more complex, and requires a database. That way, we have the producer-consumer for real pipeline processing (even if it admits local repos already) with queue, db and all and a converter which is just one command and easier for the user for the quick case we want to cover.

What do you think? @ajnavarro @bzz @mcarmonaa @marnovo

**Comment by ajnavarro** [comment]
We can skip the --source option, because always is implied, depending if you are using --file or --dir, right?

**Comment by erizocosmico** [comment]
@ajnavarro yep, you're right. Will edit the snippet

**Comment by ajnavarro** [comment]
also, --file should accept any kind of url to process, file://, http://, git and so on. we can clone any of them, so I think is worth it

**Comment by erizocosmico** [comment]
Yep, URL should accept any kind of URL

**Comment by ajnavarro** [comment]
> With --file you treat each line as a path to a repository and process it.

Should be:
With --file you treat each line as a *URL* to a repository and process it.

**Comment by erizocosmico** [comment]
Updated @ajnavarro

**Comment by ajnavarro** [comment]
LGTM

**Comment by bzz** [comment]
👍 for having separate command. 

`convert` is quite generic, may be we could try `pack` as it's going to pack things in .siva, or something like that.

Also just a thought, but `--file` kind of covers the case of `--dir`, if the dirs are `ls`ed to some file first.. so might be avoided at first impl. 

I.e AFAIK ML team does not use single dir for all 30k projects, but prefix each with some common hash subdir like `/0a/`, etc (same as `.git/objects` do), so `--dir` becomes less relevant for that uses case.

**Comment by mcarmonaa** [comment]
Is it convert the right subcommand? I mean, borges main work is aggregate repos in rooted repos and pack them in siva files, Can it generate or convert the output to other formats?

Maybe just leave it as `borges --dir` or `borges --file`is enough.

**Comment by erizocosmico** [comment]
Ok, +1 for leaving `--dir` out for now then. Which makes also `--file` disappear and can become just an argument.

+1 for renaming it to `pack`. What do you guys think @ajnavarro @mcarmonaa?

**Comment by ajnavarro** [comment]
> EDIT: perhaps we should leave the --file for when --dir is implemented and just add a shortcut -f

Yes, just in case we want to add more params in the future, to preserve the backwards compatibility.
