### ISSUE TITLE
Change go-git protocol implementation to push to siva files

### ISSUE THREAD

**Issue by ajnavarro** [src-d/borges#181]
Instead of register one protocol per push, use `siva://path/to/siva/file.siva` to push to a specific siva file.

**Comment by erizocosmico** [comment]
After a look at it, it's not necessary for the URL to be `siva://[path to siva file]`, because this step is after opening the file using the RootedTransactioner, so it does not matter to pass it the file or not. I mean, the `storer.Storer` is already available, the only thing missing is making it available in the client for the duration of the `WithInProcRepository` callback.

Unless we want to change as well how all the other things work together and remove these responsibilities from the RootedTransactioner and copier.

For now, what I'm gonna do is the following:

- Create a `sivaLoader` that will accept `siva://[hash]` URLs (the hash could be potato or an unique number just as easily, because it's only a mapping from hash to storer).
- A protocol installer that will install the protocol only once and only after the first time it needs to be installed, will install a server client using a global instance of `sivaLoader`
- In every `WithInProcRepository` a new hash to storer mapping is added at the beginning and removed at the end from the global instance of `sivaLoader`, making it available in the client without needing to install it more than once and, thus, solving the issue with the synchronization
