### ISSUE TITLE
Add rooted repos index to database

### ISSUE THREAD

**Issue by jfontan** [src-d/borges#197]
Rooted repos are now kept in a json blob inside the database. The should be a field where the rooted repos are kept for searching.

One of the use cases is setting to error all the repos that have a common rooted repo.

**Comment by erizocosmico** [comment]
### Current status

Right now, every `Repository` has the references in a slice of `*Reference`, which kallax turns into a JSON. That's not very easy to query, though.

### Proposed changes

Instead of this, I think we should promote the `Reference` entity to its own table. Making it a full-fledged entity and adding the `Repository *Repository` field for accessing the repository. There is no need to remove the `References []*Reference` from the `Repository` entity, as kallax will take care of that and turn it into a 1:N relationship.

I was thinking of making the PK a composite PK with RepositoryID and Reference name but kallax does not support composite PKs, so a new ULID will have to do instead.

We should add an index for `init` and `repository_id`, too. Perhaps also for `roots`?

### Questions

- Is `Init`a root commit hash? From the comment it seems like it.

### Migration

- We could start over, which is an option, given that siva files have been processed with some issues for a while.
- We could migrate it, though not with a simple SQL script because it would need ULID generations and so on. Perhaps a Go script that reads the database, converts the old models to the new ones and writes the results to their own `references` table. Then we can drop the column `references` from `repositories` and that would be it.

**Comment by ajnavarro** [comment]
> Is Init a root commit hash? From the comment it seems like it.

Yes

**Comment by jfontan** [comment]
`Init` is a root commit hash, yes.

Borges process was running for several months with the delta bug. I'm not sure if adding logic to detect these siva files and repacking them is worth the effort.

I do believe that detecting broken siva files is worth and having the changes proposed (references table) will make easier to invalidate repositories that depend on it.

**Comment by erizocosmico** [comment]
Ok, then I guess we can just erase and start over #yolo

**Comment by erizocosmico** [comment]
Closing, as this is merged, but not released or deployed since we still have to gather some metrics to evaluate what we do. Will open an issue later for that when we have the data.
