### ISSUE TITLE
Repositories explode into many Siva files

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/borges#222]
(Number of distinct Siva files, repository URL) in the current dataset:
```
(4623, 'https://github.com/android/platform_build'),
(2467, 'https://github.com/upspin/upspin'),
(1843, 'https://github.com/aosp-mirror/platform_development'),
(1571, 'https://github.com/android/platform_manifest'),
(1375, 'https://github.com/ceres-solver/ceres-solver'),
(831, 'https://github.com/golang/mobile'),
(746, 'https://github.com/golang/build'),
(568, 'https://github.com/webmproject/libwebm'),
(519, 'https://github.com/golang/net'),
(478, 'https://github.com/google/re2')
```

Something is wrong.

**Comment by ajnavarro** [comment]
Having a look more deeply, the repository `https://github.com/android/platform_build` has `14303` references (to be able to fetch them, you must change the refspec to the same we are using on borges: `refs/*:refs/*`): [references.txt](https://github.com/src-d/borges/files/1698714/references.txt)

I'm counting the total of init commits using standar git script. It is taking a lot of time, but right now on that repository we have `1455` unique init commits, and growing.

So, I think that is not an issue, just is correct but unexpected data.

**Comment by ajnavarro** [comment]
Yep, the number of init commits is correct. Feel free to open this issue again if necessary.

**Comment by vmarkovtsev** [comment]
@ajnavarro Can you please provide more details. What are these references, why they exist. Most likely even if they are legit we would want to have an option or a threshold to ignore them in the dataset. Let me explain why. 4k references, each taking 50MB are 10% size of the whole dataset. It is a bit too much for researchers. I need to understand the data and decide if we need it.

**Comment by vmarkovtsev** [comment]
BTW I cannot reopen this - no button.

**Comment by erizocosmico** [comment]
@vmarkovtsev right now we download absolutely every single reference the repository has in borges. Some of them have a root commit (commit with no parents) that is different from the one in master. That's why they are split in several siva files. That's how the whole concept of rooted repositories works, so that if another repository has a root commit that matches, it's added there. Siva files are not organized per repository, but per root commit.

And yes, you probably don't want all the references, unless you plan on counting all commits in all refs or all refs. If you remove that from the requirements, only HEAD will suffice (borges does not do that, tho).

**Comment by vmarkovtsev** [comment]
@erizocosmico Sure, this how is written in the paper, we dully understand this. However, it appears we need to filter the data. All data science requires data filtering, this is not somebody's fault. The problem exists, let's do a proper research and decide what to do. On one side, references must be cloned - this is a key contribution. On the other, cloning ALL the references is undesirable. I need to understand when to desire references and when not. To do this I request more information.

**Comment by ajnavarro** [comment]
> @ajnavarro Can you please provide more details. 

Sure.

> What are these references, why they exist.

Googling by the name of the references, appears that they are using Gerrit to manage the git repository [updates.](https://gerrit-review.googlesource.com/Documentation/config-project-config.html)

Every change contains a `.*/meta` reference that is a orphan reference with data like build status, comments, and so on:
[meta_out.txt](https://github.com/src-d/borges/files/1699363/meta_out.txt)

> Most likely even if they are legit we would want to have an option or a threshold to ignore them in the dataset.

How should be this option? The more straightforward thing for me is allow to set the refspec used to fetch repositories. Even with that, we are going to miss "legit" references.

The same for the threshold; How to apply it? depending of the depth of the history of the reference?, just the first n references?, or maybe the most newer ones? It depends a lot of what do you want to do with that repositories, that's why we are fetching everything.

> Let me explain why. 4k references, each taking 50MB are 10% size of the whole dataset. It is a bit too much for researchers. I need to understand the data and decide if we need it.

I cannot understand why each of that references takes 50mb, How did you get this numbers?

**Comment by vmarkovtsev** [comment]
Thanks! The hypothesis was that those Siva files were of equal size, and the packfile of a clean `git clone` was 50MB. Now that I know the nature of this explosion, this does not seem true anymore. I asked @warenlg to calculate the precise sizes of the Siva files from the list in the issue description. If it appears that they are 50MB + 4622x1KB, there is no problem - I will add a remark to the dataset description and close this.

However, if it is 50MBx4623, we will have to answer the exact questions @ajnavarro asks: how should be an option or a threshold. Together :smile:

**Comment by warenlg** [comment]
In this gist, I looked at siva files sizes belonging to github.com/android/platform_build
https://gist.github.com/warenlg/09d5712f37834417de88763ca0dd0e18

**Comment by vmarkovtsev** [comment]
```
total : 75173.7 KB
min : 2.2 KB
max : 59300.0 KB
average : 30.5 KB
```

This is resolved. The conclusion: these thousands of refs are tiny and do not pollute the dataset.
