### ISSUE TITLE
Losing the connection with the queue causes borges restart

### ISSUE THREAD

**Issue by ajnavarro** [src-d/borges#269]
The last borges version (0.12.1) restarts with the following error:

```
t=2018-04-25T01:31:44+0000 lvl=eror msg="amqp connection error" err="Exception (501) Reason: \"write tcp 10.2.20.12:41002->10.3.0.164:5672: write: connection reset by peer\""
```

**Comment by kuba--** [comment]
The issue looks that `borges consumer` had problems with connection to a _broker_ (rabbitmq). 
After polling _rabbitmq_ every second at some point a pod was killed by k8s manager and exited with error code *137* (128 + 9 -> `kill -9`). It's a pretty well known thing in k8s for pods which consume too much memory etc. (see https://github.com/kubernetes/kubernetes/issues/19825)

As a _just in case_ solution I propose to improve our _backoff_ strategy in `framework/queue/amqp.go`.
So far we have `AMQPBroker.manageConnection` which in case of errors recreates an error channel:
```
for {
		select {
		case err := <-b.connErrors:
//..
			if err != nil {
				b.conn, b.ch = connect(url)

				b.connErrors = make(chan *amqp.Error)
//..
			}
```

And `amqp.connect` function which iterates every second trying to establish connection:
```
for {
		conn, err = amqp.Dial(url)
		if err != nil {
			<-time.After(1 * time.Second)
			continue
		}
```

Instead of fixed 1 sec. interval lets use dynamic interval. which we can increate about 200ms for each iteration but up to 1 minute. 
It also would be good to avoid creating a new channel for each iteration, but because it's a bigger change lets do it eventually in the next step.

**Comment by rporres** [comment]
dmesg from the server where this pod runs

```
[Wed Apr 25 01:24:26 2018] Out of memory: Kill process 13838 (borges) score 1790 or sacrifice child
[Wed Apr 25 01:24:26 2018] Killed process 13838 (borges) total-vm:162398980kB, anon-rss:156331552kB, file-rss:4kB, shmem-rss:13320kB
[Wed Apr 25 01:24:28 2018] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[Wed Apr 25 01:24:40 2018] oom_reaper: reaped process 13838 (borges), now anon-rss:2048kB, file-rss:0kB, shmem-rss:0kB
```
