### ISSUE TITLE
Travis fails on master (go dep issue)

### ISSUE THREAD

**Issue by smola** [src-d/borges#315]
Sanity checks for non-changed files fail on Travis master. This might require pinning `go dep` to the latest release instead of using master with `go git`, just as we did in other projects.

https://travis-ci.org/src-d/borges/jobs/413710734

**Comment by jfontan** [comment]
The problem is that the latest release of go dep has a different lock file output. There's already a CI PR to install only releases instead of master as the output files were changed in master from time to time:

* https://github.com/src-d/ci/issues/83
* https://github.com/src-d/ci/pull/84

Meanwhile I would update lock file with the latest go dep version.

**Comment by kuba--** [comment]
So I hope this can be closed

**Comment by jfontan** [comment]
I would leave it open until the CI changes are made an we use only releases instead of `master`.
