### ISSUE TITLE
linejobiter_test.go uses the main database to execute the tests.

### ISSUE THREAD

**Issue by ajnavarro** [src-d/borges#63]
We should use the specific test suite in https://github.com/src-d/core/blob/master/test/suite.go to create the specific database for this tests.

You can see an example of how to use in https://github.com/src-d/borges/blob/master/archiver_test.go#L30

**Comment by alcortesm** [comment]
# Data Retrieval Sprint #17 Planning:

The current tests interfere with real data from ordinary runs of the program as both are using the same database.  A good solution is for tests to use different database (in the same DBMS).

@ajnavarro pointed out that https://github.com/src-d/borges/blob/master/archiver_test.go#L30 is already solving that same issue in another project.  I will try to solve this in a way so that we don't make the same mistake again and we don't have to solve it repeatedly in several places.
